services:
  sermulher-frontend:
    container_name: sermulher_frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_DIRECTUS_URL=http://192.168.0.115:8055
    restart: always
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      # Comunicação Interna (Container -> Container)
      - DIRECTUS_API_URL=http://direcuts_sermulher-directus-1:8055
      - DIRECTUS_TOKEN=j8EbY77uaPAhN0ZnGrDvoQI9VUGTvl_7
      - AUTH_SECRET=j8EbY77uaPAhN0ZnGrDvoQI9VUGTvl_7
      - NEXT_PUBLIC_APP_URL=https://fluxo.sermulher.aracaju.se.gov.br

    # Conecta apenas na rede do Directus que existe
    networks:
      - directus_network

networks:
  # Mapeia 'directus_network' para o nome real descoberto no servidor
  directus_network:
    external: true
    name: direcuts_sermulher_directus_net
