services:
  sermulher-frontend:
    container_name: sermulher_frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # ATENÇÃO SÊNIOR: Se o cliente precisar carregar imagens direto do Directus, 
        # idealmente o Directus também precisará de um domínio HTTPS (ex: api-sermulher.aracaju.se.gov.br).
        # Por enquanto, vamos manter como está, mas esteja ciente do bloqueio de Mixed Content.
        - NEXT_PUBLIC_DIRECTUS_URL=http://192.168.0.115:8055
    restart: always
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - DIRECTUS_API_URL=http://host.docker.internal:8055
      - DIRECTUS_TOKEN=j8EbY77uaPAhN0ZnGrDvoQI9VUGTvl_7
      - AUTH_SECRET=j8EbY77uaPAhN0ZnGrDvoQI9VUGTvl_7
      # CORREÇÃO CRÍTICA: Informa ao Next.js qual é a sua verdadeira identidade na web
      - NEXT_PUBLIC_APP_URL=https://fluxo-sermulher.aracaju.se.gov.br
    extra_hosts:
      - "host.docker.internal:host-gateway"