name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # Aciona o script local do servidor de produção.
      # O script realiza pull do código e reconstrói os containers Docker.
      - name: Executar Script de Deploy
        run: bash /opt/sermulher_gestao/deploy.sh
